.PHONY: download generate



generate:
	go generate

# specification for the listenbrainz api provided by me :D
download:
	curl https://raw.githubusercontent.com/elee1766/listenbrainz-labs-openapi/refs/heads/master/schema.yaml > schema.yaml
